# Generated by Django 5.0 on 2023-12-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
