# Generated by Django 5.0 on 2023-12-25 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0004_alter_car_model_price_alter_car_model_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='car_model',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.brand_model'),
        ),
    ]
