# Generated by Django 5.0 on 2023-12-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0006_comments_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments_model',
            old_name='post',
            new_name='car',
        ),
        migrations.AlterField(
            model_name='car_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_app/media/uploads/'),
        ),
    ]
