# Generated by Django 5.0 on 2023-12-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0008_brand_model_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='model',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
