# Generated by Django 5.0 on 2023-12-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0006_paymentmethods_model_remove_purchase_model_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_model',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
